sonar.projectKey=bank-of-anthos-ledgerwriter-project-key
sonar.organization=boa-sonar-token

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=**/generated/**,**/proto/**

sonar.java.binaries=target/classes
sonar.java.libraries=target/dependency/*.jar

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8